### ISSUE TITLE
POET logo

### ISSUE THREAD

**Issue by PouriaSterling** [agiledigital/poet-slack-bot#34]
Could anyone please send me the original copy of the POET logo (as seen in the 'Overall Architecture' section of the readme). 

I have resumed development on this project and would like to use the logo. I've been advised that @dongxuDX you were the main developer, your help would be appreciated.

**Comment by dongxuDX** [comment]
Hi @PouriaSterling,

Sorry for the late response. Please find the pic you requested in the attached.
![poet slack bot](https://user-images.githubusercontent.com/16287080/34027887-5130db80-e125-11e7-9a0e-3d509238a953.png)

Please be aware that the logo is due to @sabiipoks. I did nothing here. 

Enjoy.

**Comment by dxli94** [comment]
Hi @PouriaSterling,

Sorry for the late response. Please send me a mail at u5886609@anu.edu.au. I shall send you the file requested.

Also, please be advised that the logo is due to @sabiipoks. I did nothing here.

Cheers.
